name: mapboxnav
description: "A Flutter plugin that enables developers to integrate **Mapbox Navigation** (Turn-by-Turn) into their applications. This plugin bridges Flutter with Mapbox's powerful native navigation SDKs."
version: 1.1.7+11
homepage: https://github.com/gellsonmesquita/mapbox-nav-plugin
repository: https://github.com/gellsonmesquita/mapbox-nav-plugin

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.31
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.plugin.mapboxnav
        pluginClass: MapboxnavPlugin
      ios:
        pluginClass: MapboxnavPlugin
